conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.main.views.dashboard.views import DashboardView
from core.startpage.views import StartPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('core.main.urls')),
    path('user/', include('core.user.urls')),
    path('login/', include('core.login.urls')),
    path('startpage/', include('core.startpage.urls')),
    # Dashboard
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('', StartPageView.as_view(), name='startpage'),
    path('<int:pk>/', StartPageView.as_view(), name='startpage'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/main/urls.py
from django.urls import path

from core.main.views.category.views import *
from core.main.views.client.views import ClientView
from core.main.views.product.views import ProductView
from core.main.views.sale import views
from core.main.views.sale.views import SaleCreateView, SaleListView, \
    SaleUpdateView, ReportSaleView, SalePDF

app_name = 'main'
urlpatterns = [
    # Category
    path('category/', CategoryView.as_view(), name='category_list'),
    # Product
    path('product/', ProductView.as_view(), name='product_list'),
    # Client
    path('client/', ClientView.as_view(), name='client_list'),
    # Sale
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/update/<int:pk>/', SaleUpdateView.as_view(), name='sale_update'),
    path('sale/report/', ReportSaleView.as_view(), name='sale_report'),
    path('sale/invoice/pdf/<int:pk>/', SalePDF.as_view(), name='sale_invoice_pdf'),
    # path('sale/invoice/pdf/<int:pk>/', views.export_pdf, name='export-pdf'),
]

core/startpage/urls.py
from django.urls import path

from core.startpage import views
from core.startpage.views import CartListView

app_name = 'startpage'
urlpatterns = [
    path('cart/', CartListView.as_view(), name='cart_list'),
    path('cart/invoice/pdf/<int:pk>/', views.export_pdf, name='export-pdf'),
]

core/user/urls.py
from django.urls import path

from core.user.views import *

app_name = 'user'

urlpatterns = [
    # User
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

core/main/views/dashboard/views.py
import json
from datetime import datetime
from random import randint

from crum import get_current_request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from core.main.forms import TaskForm
from core.main.models import Category, Product, Client, Sale, DetSale, Task
from core.startpage.models import Cart, DetCart
from core.user.models import User, UserProfile


def get_graph_sales_products_year_month():
    data = []
    year = datetime.now().year
    month = datetime.now().month
    try:
        total = 0.00
        for p in Product.objects.all():
            for i in DetSale.objects.filter(sale__date_joined__year=year, sale__date_joined__month=month,
                                            prod_id=p.id):
                total += float(i.subtotal)
            if total > 0:
                data.append({
                    'name': p.name,
                    'y': float(total)
                })
                total = 0.00
    except:
        pass
    return data


def get_graph_sales_years_month():
    data = []
    try:
        year = datetime.now().year
        total = 0.00
        for m in range(1, 13):
            for i in Sale.objects.filter(date_joined__year=year, date_joined__month=m):
                total += float(i.total)
            data.append(float(total))
            total = 0.00
    except:
        pass
    return data


def task_made(request):
    return Task.objects.filter(owner_id=request.user.id) \
        .filter(status=True).count() if not request.user.is_staff else Task.objects.filter(
        status=True).count()


def my_tasks(request):
    return Task.objects.filter(owner_id=request.user.id) \
        .filter(status=False).count()


class DashboardView(TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # def get(self, request, *args, **kwargs):
    #     request.user.get_group_session()
    #     return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_graph_sales_years_month':
                data = {
                    'name': 'Percentage of sales',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': get_graph_sales_years_month()
                }
            elif action == 'get_graph_sales_products_year_month':
                data = {
                    'name': 'Percentage',
                    'colorByPoint': True,
                    'data': get_graph_sales_products_year_month()
                }
            elif action == 'get_graph_online':
                data = {'y': randint(1, 100)}
            elif action == 'search_product':
                data = Product.objects.get(pk=request.POST['id']).toJSON()
            elif action == 'search_details-prod':
                data = [i.toJSON() for i in DetCart.objects.filter(cart_id=request.POST['id'])]
            elif action == 'state':
                with transaction.atomic():
                    task = Task.objects.get(pk=request.POST['id'])
                    task.status = json.loads(request.POST['status'])
                    task.save()
                    data['task_made'] = task_made(request)
                    data['my_tasks'] = my_tasks(request)
            elif action == 'del_task':
                with transaction.atomic():
                    task = Task.objects.get(pk=request.POST['id'])
                    data['task'] = task.toJSON()
                    task.delete()
                    data['task_made'] = task_made(request)
                    data['my_tasks'] = my_tasks(request)
            elif action == 'task_add':
                with transaction.atomic():
                    print(request.POST)
                    if request.POST['id'] == '-1':
                        task = Task()
                        data['edit'] = '0'
                    else:
                        task = Task.objects.get(pk=request.POST['id'])
                        data['edit'] = '1'
                    task.owner_id = request.POST['owner']
                    task.text = request.POST['text']
                    task.save()
                    data['task'] = task.toJSON()
                    data['task_made'] = task_made(request)
                    data['my_tasks'] = my_tasks(request)
            elif action == 'get_All_Task':
                data = [t.get_Time() for t in Task.objects.all()]
            elif action == 'get_task_by_id':
                data = Task.objects.get(pk=request.POST['id']).toJSON()
            elif action == 'get_user':
                user = User.objects.get(pk=request.POST['id'])
                data['data'] = UserProfile.objects.get(user_id=request.POST['id']).toJSON()
                data['total_sales'] = Sale.objects.filter(user_creation_id=user.id).count() + \
                                      Cart.objects.filter(user_updated_id=user.id).count()
                data['prods_added'] = Product.objects.filter(user_creation=user.id).count()
                data['my_tasks'] = Task.objects.filter(owner_id=user.id).filter(status=False).count()
            else:
                data['error'] = 'Sigue tirando perlies'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Admin panel'
        context['title'] = 'Dashboard'
        context['graph_sale_years'] = get_graph_sales_years_month()
        context['entity_count'] = countEntity()
        context['sales_at_home'] = [c for c in Cart.objects.order_by('-date_joined')
            .order_by('-id').exclude(status='Sold').exclude(cli_addr='Our local')][:4]
        context['task_form'] = TaskForm()
        context['list_url'] = reverse_lazy('dashboard')
        context['entity'] = 'Dashboard'
        # context['prods_sold'] = DetSale.objects.filter(prod__in=Product.objects.all()).count()
        return context

    def get(self, request, *args, **kwargs):
        kwargs['get_users'] = [user for user in User.objects
            .filter(date_joined__lt=request.user.last_login).exclude(pk=request.user.pk)][:8]
        kwargs['users_count'] = len(kwargs['get_users'])
        kwargs['last_products'] = Product.objects.filter().order_by('-date_creation')[:4]
        kwargs['total_sales'] = Sale.objects.filter(user_creation_id=request.user.id).count() + \
                                Cart.objects.filter(user_updated_id=request.user.id).count()
        kwargs['prods_added'] = Product.objects.filter(user_creation=request.user.id).count()

        kwargs['tasks'] = Task.objects.all() if request.user.is_staff else Task.objects.filter(owner_id=request.user.id)
        kwargs['my_tasks'] = Task.objects.filter(owner_id=request.user.id).filter(status=False).count()
        kwargs['task_made'] = task_made(request)
        return super().get(request, *args, **kwargs)


def countEntity():
    request = get_current_request()
    return {
        'cat': Category.objects.filter(date_creation__gt=request.user.last_login).count(),
        'prod': Product.objects.filter(date_creation__gt=request.user.last_login).count(),
        'cli': Client.objects.filter(pk__in=Sale.objects.all()).count(),  # clientes q tengan ventas hechas
        'sale': Sale.objects.filter(date_joined__gt=request.user.last_login).count(),
        'user': User.objects.filter(date_joined__gt=request.user.last_login).count(),
        'cart': Cart.objects.filter(date_joined__gt=request.user.last_login).count()
    }

templates/asd.html
<div id="con-close-modal" class="modal fade show" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     style="display: block; padding-right: 17px;" aria-modal="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Modal Content is Responsive</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body p-4">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="field-1" class="control-label">Name</label>
                            <input type="text" class="form-control" id="field-1" placeholder="John">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="field-2" class="control-label">Surname</label>
                            <input type="text" class="form-control" id="field-2" placeholder="Doe">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Address</label>
                            <input type="text" class="form-control" id="field-3" placeholder="Address">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="field-4" class="control-label">City</label>
                            <input type="text" class="form-control" id="field-4" placeholder="Boston">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="field-5" class="control-label">Country</label>
                            <input type="text" class="form-control" id="field-5" placeholder="United States">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="field-6" class="control-label">Zip</label>
                            <input type="text" class="form-control" id="field-6" placeholder="123456">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <label for="field-7" class="control-label">Personal Info</label>
                            <textarea class="form-control" id="field-7"
                                      placeholder="Write something about yourself"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info waves-effect waves-light">Save changes</button>
            </div>
        </div>
    </div>
</div>

templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            {% block content_header %}
                <div class="content-header py-2">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1 class="m-0 text-dark pl-lg-5"> Welcome
                                    <small>{{ request.user.get_full_name }}</small></h1>
                            </div>
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right pr-lg-5">
                                    <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                                    <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            <div class="content px-0">
                <div class="container-fluid px-lg-5">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
        {% include 'modal_links.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}

    </body>
{% endblock %}

templates/footer.html
{% load static %}
<!-- Main Footer -->
<footer class="main-footer p-2 text-center user-select-none">
    <strong>Copyright &copy; <span id="year"></span> <a href="#">Techno$TΛЯ™</a></strong><br>
    All rights reserved.
</footer>
<script>
  if (new Date().getFullYear() === 2021)
    document.getElementById('year').innerHTML = `2021`
  else
    document.getElementById('year').innerHTML = `2021-${new Date().getFullYear()}`
</script>

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-indigo" id="header">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="mdi mdi-menu mdi-18px"></i></a>
        </li>
        <li>
            <a class="nav-link pl-0 cursor-pointer" data-toggle="modal" data-target="#links"
               role="button">
                <i class="mdi mdi-link-variant mdi-18px"></i></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'dashboard' %}" class="nav-link pl-0"><i
                    class="mdi mdi-home d-sm-inline-block pl-0 pr-0"></i>
                <span class=" d-none d-sm-inline-block"> Home</span>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <a href="#"></a>
        {% if request.user.groups.all %}
            <li class="nav-item dropdown show">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                   class="nav-link{% if request.user.groups.all.count > 1 %}
                       {% endif %}  dropdown-toggle">{{ request.session.group }}</a>

                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0; right: inherit;min-width: auto">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item circular">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="mdi mdi-account-settings mdi-18px"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header truncate-1" style="font-size: 12px;">
                       You last login was {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_update' request.user.id %}" class="dropdown-item">
                    <i class="mdi mdi-account-edit mdi-18px mr-2"></i> Edit profile
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                    <i class="mdi mdi-lock mdi-18px mr-2"></i> Edit password
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer circular-bottom" >
                    <p>bla bla bla bla bla</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="mdi mdi-power" style="font-size: 20px" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/layout.html
{% extends 'body.html' %}

templates/modal_links.html
{% load widget_tweaks %}
<div class="modal fade" id="links" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true" style="min-width: 350px">
    <div class="modal-dialog modal-sm modal-dialog-top modal-dialog-slideup" role="document">
        <div class="modal-content circular">
            <div class="modal-header bg-gradient-info circular-top">
                <h5 class="modal-title">
                    <i class="mdi mdi-link-variant mdi-18px"></i> Quick access
                </h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'startpage:cart_list' %}"
                       target="_blank">

                            <span class="badge bg-info circular">{{ entity_count.cart }}</span>
                        <i class="mdi mdi-cart mdi-24px d-block"></i> Sales online
                    </a>
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'main:sale_create' %}" target="_blank">
                        <span class="badge bg-info circular">{{ entity_count.sale }}</span>
                        <i class="mdi mdi-cart-plus mdi-24px d-block"></i> Sales
                    </a>
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'user:user_list' %}" target="_blank">
                        <span class="badge bg-warning circular">{{ entity_count.user }}</span>
                        <i class="mdi mdi-account-multiple mdi-24px d-block"></i> Users
                    </a>
                </div>
                <div class="row">
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'main:category_list' %}"
                       target="_blank">
                        <span class="badge bg-teal circular">{{ entity_count.cat }}</span>
                        <i class="mdi mdi-widgets mdi-24px d-block"></i> Categories
                    </a>
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'main:product_list' %}" target="_blank">
                        <span class="badge bg-teal circular">{{ entity_count.prod }}</span>
                        <i class="mdi mdi-package-variant d-block mdi-24px"></i> Products
                    </a>
                    <a class="btn btn-app pt-0 text-body circular" href="{% url 'main:client_list' %}" target="_blank">
                        <span class="badge bg-success circular">{{ entity_count.cli }}</span>
                        <i class="mdi mdi-account-multiple-check mdi-24px d-block"></i> Clients
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/sidebar.html
{% load static %}
<aside class="main-sidebar elevation-4 sidebar-light-indigo" id="sidebar">
    <!-- Brand Logo -->
    <div class="user-panel d-flex elevation-2">
        <a href="{% url 'startpage' %}" class="brand-link border-bottom-0 py-1">
            <img src="{% static 'img/logo-sm-red-black.png' %}"
                 alt="TechnoSTAR Logo"
                 class="d-none icon-sm" style="margin-left: 0;height: 49px;width: 45.5px">

            <img src="{% static 'img/logo-lg-red-black.png' %}"
                 alt="TechnoSTAR Logo"
                 style="margin-left: 0;width: 120px;height: 49px"
                 class="icon-lg">
        </a>
        <a class="nav-link" href="#">
            <i class="mdi mdi-weather-night mdi-24px text-black-50" aria-hidden="true" id="theme"></i>
        </a>
    </div>
    <div class="sidebar pl-0">

        <div class="user-panel mt-3 d-flex border-bottom-0">
            <a href="#" class="image">
                <img alt
                     src="{% if request.user.get_image %}{{ request.user.get_image }}{% else %}{% static 'img/user2.png' %}{% endif %}"
                     class="img-circle elevation-1"
                     style="width: 37px;height: 37px">
            </a>
            <div class="info">
                <a href="#" class="d-block">{% if request.user.get_full_name %}{{ request.user.first_name }} | {{ request.user.username }}
                    {% elif request.user.username %}{{ request.user.username }}{% else %}Guest{% endif %}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview"
                role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <div class="my-2 ml-1" style="border-top: 1px solid #4f5962"></div>
                <li class="nav-item has-treeview">
                    <a href="{% url 'dashboard' %}" class="nav-link active my-dash">
                        <i class="nav-icon mdi mdi-monitor-dashboard"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview ">
                    <a href="#" class="nav-link my-stored">
                        <i class="nav-icon mdi mdi-store"></i>
                        <p>
                            Availability stored
                            <i class="right mdi mdi-menu-left-outline"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'main:category_list' %}" class="nav-link my-stored-cat">
                                <i class="mdi mdi-widgets nav-icon"></i>
                                <p>Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'main:product_list' %}" class="nav-link my-stored-prod">
                                <i class="mdi mdi-package-variant-closed nav-icon"></i>
                                <p>Products</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link my-accounts">
                        <i class="nav-icon mdi mdi-account-multiple-check"></i>
                        <p>
                            Registered accounts
                            <i class="right mdi mdi-menu-left-outline"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'main:client_list' %}" class="nav-link my-accounts-client">
                                <i class="mdi mdi-account-star nav-icon"></i>
                                <p>Clients</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="w3-light-gray nav-link my-accounts-worker">
                                <i class="mdi mdi-worker nav-icon"></i>
                                <p>Users</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link my-sales">
                        <i class="nav-icon mdi mdi-cart"></i>
                        <p>
                            Sales record
                            <i class="right mdi mdi-menu-left-outline"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'main:sale_create' %}" class="nav-link my-sales-add">
                                <i class="mdi mdi-cart-plus nav-icon"></i>
                                <p>Create sale</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'main:sale_list' %}" class="nav-link my-sales-sales">
                                <i class=" mdi mdi-finance nav-icon"></i>
                                <p>Sales list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'main:sale_report' %}" class="nav-link my-sales-reports">
                                <i class="mdi mdi-chart-bar nav-icon"></i>
                                <p>Sales report</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link my-sales-cart">
                        <i class="nav-icon mdi mdi-cart-outline"></i>
                        <p>
                            Sales online record
                            <i class="right mdi mdi-menu-left-outline"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'startpage:cart_list' %}" class="nav-link my-sales-cart-list">
                                <i class="mdi mdi-finance nav-icon"></i>
                                <p>Sales online list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'startpage' %}" class="nav-link my-sales-cart-startpage">
                                <i class="mdi mdi-settings nav-icon"></i>
                                <p>Config S. Cart </p>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
        <div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);"></div>
            </div>
        </div>
        <div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="height: 45.151%; transform: translate(0px, 0px);"></div>
            </div>
        </div>
        <div class="os-scrollbar-corner"></div>
    </div>

    <!-- /.sidebar -->
</aside>